[workspace]
members = [
  "iroh",
  "iroh-bitswap",
  "iroh-car",
  "iroh-ctl",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-one",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-store",
  "iroh-share",
  "iroh-util",
  "stores/*",
  "examples"
]

[patch.crates-io]
libp2p = { git = "https://github.com/dignifiedquire/rust-libp2p", branch = "iroh" }
# libp2p = { path = "../rust-libp2p" }

[profile.release]
lto = true
panic = "abort"